version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build_and_test: build_and_test
    executor: python/default # use the default executor defined within the orb
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
    build_and_test:
      jobs:
      - build_and_test